### ISSUE TITLE
Multi-data/layer support

### ISSUE THREAD

**Issue by eblondel** [r-geoflow/geoflow#325]
This ticket is here to reference development tasks related to the multi-layer support:
* [x] Multiple data support for a single entity #263
* [x] Merge 'enrichWithFeatures' / enrichWithCoverages' into single 'enrichWithData' #264 
* [x] Enable data enrichment strategies ('first', 'union') for spatial bounding box #265 
* [x] Support multi-source 'dir' method for remote accessors (eg. ocs) #304 
* [x] Improve 'dir' multi-source approach for geopackage support #324
* [x] Enhance ISO 19110 action for handling common data structure based multi-source features #326
